//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchAvto.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battery
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> NominalVoltage { get; set; }
    
        public virtual BatteryType BatteryType { get; set; }
    }
}
