//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchAvto.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Battery> Batteries { get; set; }
        public virtual DbSet<BatteryType> BatteryTypes { get; set; }
        public virtual DbSet<BodyClass> BodyClasses { get; set; }
        public virtual DbSet<BodyType> BodyTypes { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CarModel> CarModels { get; set; }
        public virtual DbSet<CommentsToNew> CommentsToNews { get; set; }
        public virtual DbSet<ElectricEngine> ElectricEngines { get; set; }
        public virtual DbSet<ElectricMotor> ElectricMotors { get; set; }
        public virtual DbSet<EngineLocation> EngineLocations { get; set; }
        public virtual DbSet<FuelType> FuelTypes { get; set; }
        public virtual DbSet<InternalCombustionEngine> InternalCombustionEngines { get; set; }
        public virtual DbSet<ModelLine> ModelLines { get; set; }
        public virtual DbSet<Modification> Modifications { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<TireCarcassType> TireCarcassTypes { get; set; }
        public virtual DbSet<TransmissionType> TransmissionTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ValvesArrangement> ValvesArrangements { get; set; }
    }
}
