//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchAvto.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectricMotor
    {
        public ElectricMotor()
        {
            this.ElectricEngines = new HashSet<ElectricEngine>();
            this.ElectricEngines1 = new HashSet<ElectricEngine>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<int> Torque { get; set; }
    
        public virtual ICollection<ElectricEngine> ElectricEngines { get; set; }
        public virtual ICollection<ElectricEngine> ElectricEngines1 { get; set; }
    }
}
