//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchAvto.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modification
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ModelId { get; set; }
        public Nullable<int> MaxSpeed { get; set; }
        public Nullable<double> Velocity { get; set; }
        public Nullable<byte> NumberOfSeats { get; set; }
        public Nullable<int> Length { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> CurbWeight { get; set; }
        public Nullable<int> TotalWeight { get; set; }
        public Nullable<int> CargoVolume { get; set; }
        public Nullable<int> MaxCargoVolume { get; set; }
        public Nullable<int> Wheelbase { get; set; }
        public Nullable<double> FrontTrackWidth { get; set; }
        public Nullable<double> BackTrackWidth { get; set; }
        public Nullable<int> InternalCombustionEngineId { get; set; }
        public Nullable<int> ElectricEngineId { get; set; }
        public Nullable<int> TransmissionTypeId { get; set; }
        public Nullable<int> TransmissionStages { get; set; }
        public Nullable<byte> Drive { get; set; }
        public Nullable<byte> NumberOfWheels { get; set; }
        public Nullable<byte> NumberOfDrivenWheels { get; set; }
        public Nullable<int> TireProfileWidth { get; set; }
        public Nullable<int> TireProfileHeight { get; set; }
        public Nullable<int> TireCarcassTypeId { get; set; }
        public Nullable<double> TireMountingDiameter { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual ElectricEngine ElectricEngine { get; set; }
        public virtual InternalCombustionEngine InternalCombustionEngine { get; set; }
        public virtual TransmissionType TransmissionType { get; set; }
        public virtual TireCarcassType TireCarcassType { get; set; }
    }
}
